### ISSUE TITLE
Font error

### ISSUE THREAD

**Issue by ScraperMan2002** [5hwb/Old-Hangul-Input-Method#14]
Allow me to explain:

ힽ is "ᅵ ᅣ ᅩ", right? Well, if you type it in your application, it displays "ᅵ ᅣ ᅮ". What is going on?

**Comment by ScraperMan2002** [comment]
But what's actually interesting, is if I, copy paste the "ᅵ ᅣ ᅮ" produced by your application, do "ctrl+f", and paste it on Google Chrome, it actually highlights the characters with ힽ. So it's not a bug due to the system that CREATES the hangul, it seems to be an error with the system that DISPLAYS the Hangul. So how do you fix it?

**Comment by 5hwb** [comment]
Yeah, it looks like a bug with the NanumBarunGothic YetHangul font. The Old Hangul IME's not at fault here. There are other fonts that support Old Hangul such as Noto Sans CJK KR which don't have the bug, although they don't look as nice IMO.

Out of curiosity, may I ask what are you using Old Hangul IME for - a conlang, personal project, etc?

**Comment by ScraperMan2002** [comment]
Personal Project, namely, porting Ancient Korean texts onto Wikisource.

**Comment by ScraperMan2002** [comment]
Well another error is that, if you paste "ᅢ" onto your Old Hangul IME, the text displays "ᅣ" instead, is this also a bug on the part of Old Hangul IME?

**Comment by 5hwb** [comment]
Nice, glad this project could help!

Indeed, it's another weird bug with the the NanumBarunGothic YetHangul font. I might go and update the README to recommend the use of a different Hangul font later.

**Comment by ScraperMan2002** [comment]
Oh, and that's not the end of it!
There is something wierd when you use "ꥼ" in the IME. When you type "ꥼ", and then type some sort of "Medial" thing like "ᅡ", the IME doesn't visually combine the two characters, but when you paste the combination onto some search bar on google, they combine perfectly!
Take for instance "ꥼᅡ", or "ꥼᅪᆼ〮". Try pasting them onto the IME!

**Comment by ScraperMan2002** [comment]
Have you tried the Nabi font by any chance?

https://github.com/libhangul/nabi

**Comment by 5hwb** [comment]
I've updated the IME, changed the default font from NanumBarunGothic YetHangul to Noto Sans CJK KR since it has none of the aforementioned bugs. Feel free to download the latest version.
