### ISSUE TITLE
Safari on macos

### ISSUE THREAD

**Issue by Luci6fuge** [5hwb/Old-Hangul-Input-Method#15]
Hi.

I installed "Noto Sans CJK KR" but Safari does not recognize it. (Other browsers do.)
It's silly but I had to use `@import` or `@font-face` for Safari.

[diff.txt](https://github.com/5hwb/Old-Hangul-Input-Method/files/9590987/diff.txt)

Now I am totally confused...

**Comment by 5hwb** [comment]
Cool - apologies for late response, I'll make a commit with your changes shortly
