### ISSUE TITLE
Rising and High Korean tones are not supported

### ISSUE THREAD

**Issue by ScraperMan2002** [5hwb/Old-Hangul-Input-Method#4]
You forgot to include the Rising and High Korean tones?〮 and 〯.
I however, have solved this little problem of yours.

**Comment by 5hwb** [comment]
I'm aware that archaic Hangul tone marks are currently unsupported for the time being. Nevertheless, feel free to create a pull request that implements them and I'll merge the improvements into this project.

**Comment by ScraperMan2002** [comment]
I'm new to Github, so I'm new to pull requests, but I've done what I can here by learning the tutorial.

**Comment by 5hwb** [comment]
Thanks for the pull request - this is admittedly my first time reviewing a pull request too. I've left some comments, feel free to review them and address the issues mentioned.
