### ISSUE TITLE
How do you type in "ㅸ"?

### ISSUE THREAD

**Issue by ScraperMan2002** [5hwb/Old-Hangul-Input-Method#6]
I don't understand, how do you type in ㅸ? I just can't!

**Comment by ScraperMan2002** [comment]
NVM Solved.

**Comment by 5hwb** [comment]
See the keyboard layout reference in the README:

> (ㅇ) represents the bottom half of the letters ᄛ, ᄝ, ᄫ, ᄬ, ᅗ.

To type ᄫ specifically, press ㅂ (q) + (ㅇ) (S) one after the other.
